Exception on /user/505 [GET]
Traceback (most recent call last):
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/app/main/views.py", line 33, in profile
    title = f'{user.firstName}\'s profile.'
AttributeError: 'NoneType' object has no attribute 'firstName'

Exception on /user/51 [GET]
Traceback (most recent call last):
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/virtual/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Harry King/Documents/flask_projects/flask/school_system/app/main/views.py", line 33, in profile
    title = f'{user.firstName}\'s profile.'
AttributeError: 'NoneType' object has no attribute 'firstName'
